---
title: "Session 2: Logging On and Linux Recap"
subtitle: "Connecting to Aire and Command Line Essentials"
format: html
---

In this session, we will get connected to Aire. This section is modified from the [documentation pages for Aire](https://arcdocs.leeds.ac.uk/aire/getting_started/logging_on.html). Please note that a University of Leeds account is required to view the links below.

## Logging on

The training facilitator will share their screen and take your through the steps required to log in, swapping from these notes to the KB articles linked below for the relevant session.

::: {.callout-note}
## Connection Method Depends on Location

The delivery of this session will depend whether it is hosted in-person or remotely.

To connect to the Aire platform, the steps vary depending on whether you are on the wired campus network or offsite/using Eduroam. If you are offsite, you must connect through the University's SSH gateway or use the University VPN. However, if you are on the campus network, no additional steps are required.
:::

### General instructions

To access Aire, you simply need access to an [SSH (Secure SHell) client](https://en.wikipedia.org/wiki/Secure_Shell). This could be your terminal or Bash if you are using Linux or a Mac, or PowerShell or MobaXTerm if you are using Windows.

From a wired connection on campus, use the following command in your SSH client:

```bash
ssh <username>@target-system
```

From off-campus (or using a machine on Eduroam as opposed to the wired network), just add in the provided SSH gateway/jumphost:

```bash
ssh <username>@target-system -J <username>@jump-host
```

### KB articles for connecting from campus

**For in-person sessions or for people attending remotely from an on-campus machine.**

You can connect to Aire and log in using SSH (Secure Shell) from within the University network.
Please see the following Knowledge Base articles for more information:

+ [KB0018276 - How do I connect to Aire from a Windows machine on campus?](https://it.leeds.ac.uk/it?id=kb_article_view&sysparm_article=KB0018276)
+ [KB0018275 - How do I log in to Aire on Linux or Mac OS from on Campus?](https://it.leeds.ac.uk/it?id=kb_article_view&sysparm_article=KB0018275)

Note that the above articles require you to log in with your University account to view.

### KB articles for connecting when off-site

**For online/remote sessions and connecting from a laptop not connected to the University ethernet.**

To access Aire from outside the University, you will need to connect through the University's general SSH gateway or use the University VPN, whereas access from the campus network does not require this additional step.
Please see the following Knowledge Base articles for more information:

+ [KB0018286 - How do I connect to Aire from a Windows machine off campus?](https://it.leeds.ac.uk/it?id=kb_article_view&sysparm_article=KB0018286)
+ [KB0018284 - How do I log in to Aire on Linux or Mac OS from off Campus?](https://it.leeds.ac.uk/it?id=kb_article_view&sysparm_article=KB0018284)

For more general guidance on using SSH and the VPN for remote access, please see the following Knowledge Base articles:

+ [KB0014674 - SSH remote access at the University of Leeds](https://it.leeds.ac.uk/it?id=kb_article_view&sysparm_article=KB0014674)
+ [KB0014410 - Connecting to the University VPN](https://it.leeds.ac.uk/it?id=kb_article_view&sysparm_article=KB0014410)

---

## Linux recap

[**View Interactive Slides: Linux Command Line Essentials**](logging-on-linux-slides.qmd){.btn .btn-primary target="_blank"}

### Why Command Line Interface (CLI)?

Many large research machines (such as the HPC machines ARC4 and Aire here at Leeds) do not have a GUI (Graphical User Interface) and so you need to interact with them through a CLI.

- CLIs allow us to interact with a computer through text-based commands typed into the command-line
- While GUIs can be simple and intuitive to use, they can make it difficult to reproduce workflows:
  - Sometimes you have to record by hand (or with a screen recording) what sub-options from different menus you used
  - Updates to GUIs can make it difficult to find the same menu options
  - A workflow with multiple steps can be tedious to repeat for multiple datasets

### Essential Commands

Here are some essential Linux commands you'll use frequently:

```bash
# Navigation
pwd          # Print working directory
ls           # List files and directories
cd           # Change directory

# File operations
cp           # Copy files
mv           # Move/rename files
rm           # Remove files
mkdir        # Create directory

# Viewing files
cat          # Display file contents
less         # View file contents page by page
head         # Show first few lines
tail         # Show last few lines

# System information
whoami       # Current username
df -h        # Disk usage
free -h      # Memory usage
```

---

## Next Steps

Now that you can connect to Aire and understand basic Linux commands, let's move on to [Session 3: Storage](storage.qmd) to learn about managing your data on the HPC system.

## Additional Resources

- [Aire Getting Started Guide](https://arcdocs.leeds.ac.uk/aire/getting_started/start.html)
- [Linux Command Line Tutorial](https://arc.leeds.ac.uk/courses/hpc0-introduction-to-linux-for-hpc/)
- [SSH Documentation](https://arcdocs.leeds.ac.uk/aire/getting_started/logging_on.html)
